#PBS -N CUDA-aware_MPI
#PBS -l nodes=2:ppn=2:gpus=4
#PBS -l pmem=8gb
#PBS -l walltime=00:05:00 
#PBS -q hive-gpu-short
#PBS -j oe

module use $HOME/scratch/module_files
module unload mvapich2
module load mvapich2/2.3.4

cd $PBS_O_WORKDIR

mpiname -a

make clean
make

# Rank 1 on node 0, rank 3 on node 1, should use RMA
mpirun -np 4 ./cuda_aware_mpi.x 1 3

# Ranks 1 and 0 are both on node 0, should use P2P IPC
mpirun -np 4 ./cuda_aware_mpi.x 1 0
